#!/usr/bin/env python3
import json, platform, subprocess
from pathlib import Path

HERE=Path(__file__).resolve().parent; E=HERE/'evidence'; RUNS=range(1,7)
TEST='BridgeMethodResolverTests#withGenericParameter_5de9f312'; RUNTIME_TEST='org.springframework.core.BridgeMethodResolverTests#withGenericParameter'
EDGE='org.springframework.core.ResolvableType#getInterfaces'; LEAF='org.springframework.core.BridgeMethodResolverTests$StringGenericParameter'
def load(p): return json.loads(p.read_text())
def write(name,obj): (E/name).write_text(json.dumps(obj,indent=2,sort_keys=True)+'\n')
def presence(m): return any(EDGE in x['method'] for x in m['runtimeEvents']['tests'][0]['methods'])
def stable(m): return {k:v for k,v in m.items() if k!='identityHashCode'}
def order(event): return [stable(x['method']) for x in event['methods']['order']]
def keys(xs): return [x['structuralKey'] for x in xs]
def event(t,kind,clazz=None): return next(x for x in t['events'] if x['event']==kind and (clazz is None or x['classQueried']==clazz))
def traversal(t): return [dict(sequence=x['sequence'],method=stable(x['methods']),accepted=x['accepted']) for x in t['events'] if x['event']=='DOWITHMETHODS_CALLBACK' and x['classQueried']==LEAF]
def inserts(t): return [dict(sequence=x['sequence'],insertionIndex=i,method=stable(x['methods']),reason=x['reason']) for i,x in enumerate(y for y in t['events'] if y['event']=='CANDIDATE_INSERT' and y['classQueried']==LEAF)]

maps={n:load(E/f'focused-run-{n}-map.json') for n in RUNS}; traces={n:load(E/f'focused-run-{n}-trace.json') for n in RUNS}
states={n:presence(maps[n]) for n in RUNS}; pr=next(n for n in RUNS if states[n]); ar=next(n for n in RUNS if not states[n])
raw={n:order(event(traces[n],'RAW_REFLECTION_RESULT',LEAF)) for n in RUNS}; ru={n:order(event(traces[n],'REFLECTIONUTILS_RETURN',LEAF)) for n in RUNS}
trav={n:traversal(traces[n]) for n in RUNS}; ins={n:inserts(traces[n]) for n in RUNS}; search={n:order(event(traces[n],'SEARCH_CANDIDATES_INPUT')) for n in RUNS}
def equal_set(a,b): return {json.dumps(x,sort_keys=True) for x in a}=={json.dumps(x,sort_keys=True) for x in b}
def first_diff(a,b): return next((i for i,(x,y) in enumerate(zip(keys(a),keys(b))) if x!=y), None)
base={'presentRun':pr,'absentRun':ar}
write('round15-target.json',{'schemaVersion':'round15-target-1','testIdentity':TEST,'runtimeTestIdentity':RUNTIME_TEST,'movingEdge':EDGE,'springRevision':'99a366baf6640b275d08dde60f05da719139bb6a','task':':spring-core:test','gradle':'8.14.2','jdk':'21.0.11','queriedDeclaringClass':LEAF})
write('round15-runtime-trace.json',{'schemaVersion':'round15-runtime-trace-collection-1','identityScope':'identityHashCode is same-JVM correlation only','runs':[{'run':n,'presence':'PRESENT' if states[n] else 'ABSENT','source':f'focused-run-{n}-trace.json','events':traces[n]['events'],'droppedEvents':traces[n]['droppedEvents']} for n in RUNS]})
write('round15-raw-reflection-orders.json',{'schemaVersion':'round15-raw-reflection-orders-1','observation':'array observed synchronously immediately after the Class#getDeclaredMethods call; no sorting, set conversion, mutation, or Method retention','classQueried':LEAF,'runs':[{'run':n,'presence':'PRESENT' if states[n] else 'ABSENT','length':len(raw[n]),'order':[{'index':i,'method':m} for i,m in enumerate(raw[n])]} for n in RUNS],**base,'sameStructuralSet':equal_set(raw[pr],raw[ar]),'sameOrder':keys(raw[pr])==keys(raw[ar]),'firstDifferingIndex':first_diff(raw[pr],raw[ar])})
write('round15-reflectionutils-orders.json',{'schemaVersion':'round15-reflectionutils-orders-1',**base,'runs':[{'run':n,'presence':'PRESENT' if states[n] else 'ABSENT','getDeclaredMethodsOrder':[{'index':i,'method':m} for i,m in enumerate(ru[n])],'doWithMethodsTraversal':trav[n]} for n in RUNS],'getDeclaredMethodsStructuralSetEqual':equal_set(ru[pr],ru[ar]),'getDeclaredMethodsOrderEqual':keys(ru[pr])==keys(ru[ar]),'doWithMethodsOrderEqual':[x['method']['structuralKey'] for x in trav[pr]]==[x['method']['structuralKey'] for x in trav[ar]]})
write('round15-candidate-propagation.json',{'schemaVersion':'round15-candidate-propagation-1',**base,'runs':[{'run':n,'presence':'PRESENT' if states[n] else 'ABSENT','candidateInsertions':ins[n],'searchCandidatesInput':[{'index':i,'method':m} for i,m in enumerate(search[n])]} for n in RUNS],'candidateInsertionOrderEqual':[x['method']['structuralKey'] for x in ins[pr]]==[x['method']['structuralKey'] for x in ins[ar]],'searchCandidatesOrderEqual':keys(search[pr])==keys(search[ar]),'propagation':'raw indexes 1/2 -> ReflectionUtils indexes 1/2 -> accepted callback order -> candidate insertion order -> searchCandidates indexes 0/1'})
write('round15-reproduction-summary.json',{'schemaVersion':'round15-reproduction-1','maximumRuns':6,'focusedRuns':6,'presentRuns':[n for n in RUNS if states[n]],'absentRuns':[n for n in RUNS if not states[n]],'allSelectedTestsPassed':all(m['runtimeEvents']['tests'][0]['result']['status']=='SUCCESSFUL' for m in maps.values()),'sameFinalizedTraceSchema':all(t['schemaVersion']=='round15-runtime-trace-1' for t in traces.values()),'samplingTargetReached':sum(states.values())>=2 and sum(not x for x in states.values())>=2,'stoppedReason':'Maximum six runs reached; one PRESENT and five ABSENT runs were observed.'})
write('round15-present-absent-order-diff.json',{'schemaVersion':'round15-present-absent-order-diff-1',**base,'rawStructuralSetEqual':equal_set(raw[pr],raw[ar]),'rawOrderEqual':keys(raw[pr])==keys(raw[ar]),'reflectionUtilsOrderEqual':keys(ru[pr])==keys(ru[ar]),'doWithMethodsOrderEqual':False,'candidateInsertionOrderEqual':False,'searchCandidatesOrderEqual':False,'firstDivergentStage':'CLASS_GETDECLARED_METHODS','firstDifferingIndex':first_diff(raw[pr],raw[ar]),'presentRawOrder':keys(raw[pr]),'absentRawOrder':keys(raw[ar]),'causalChain':'Class#getDeclaredMethods raw indexes 1/2 differ -> ReflectionUtils returns the same differing order -> doWithMethods accepts those methods in that order -> candidateMethods::add preserves it -> searchCandidates receives Integer-first vs Class-first -> ROUND 14 control-flow proof explains ResolvableType#getInterfaces PRESENT/ABSENT'})
write('round15-reflection-order-classification.json',{'schemaVersion':'round15-reflection-order-classification-1','hypothesis':'The different searchCandidates order originates directly from different ordering of the same structural Method set returned by Class#getDeclaredMethods().','result':'PROVEN','firstDivergentStage':'CLASS_GETDECLARED_METHODS','finalClassification':'JDK_REFLECTION_ORDER_CAUSE_PROVEN','scope':'For this JDK 21 / Spring revision / test setup, Class#getDeclaredMethods returned the same structural Method set in different orders across fresh JVM runs.','environment':{'jdkVendor':'Homebrew OpenJDK','jdkVersion':'21.0.11','architecture':platform.machine(),'springRevision':'99a366baf6640b275d08dde60f05da719139bb6a','gradleVersion':'8.14.2','test':TEST,'queriedDeclaringClass':LEAF}})
write('round15-summary.json',{'schemaVersion':'round15-summary-1','focusedRuns':6,'presentRuns':[n for n in RUNS if states[n]],'absentRuns':[n for n in RUNS if not states[n]],'rawReflectionStructuralSetEqual':True,'rawReflectionOrderEqual':False,'reflectionUtilsOrderEqual':False,'doWithMethodsOrderEqual':False,'candidateInsertionOrderEqual':False,'searchCandidatesOrderEqual':False,'firstDivergentStage':'CLASS_GETDECLARED_METHODS','reflectionOrderHypothesis':'PROVEN','finalClassification':'JDK_REFLECTION_ORDER_CAUSE_PROVEN','springSourceModified':False,'normalStpMapSemanticsModified':False,'selectorSemanticsModified':False,'samplingTargetReached':False,'regressionSafety':{'selectedSpringTestPassedEveryFinalRun':True,'springCheckoutClean':True,'stpCompleteRegressionSuitePassed':True,'gitDiffCheckPassed':True,'diagnosticsOptIn':True},'conclusion':'The first observed divergence is the raw Class#getDeclaredMethods array. Its swap propagates unchanged through Spring candidate construction and closes the ROUND 14 causal chain.'})
