// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Smart Test Picker contributors
// SPDX-License-Identifier: Apache-2.0
package com.sap.oss.smarttestpicker.springdata;

enum RepositoryEligibilityReason {
	ELIGIBLE,
	MISSING_FACTORY_METADATA,
	NON_ADVISED_REPOSITORY,
	REPOSITORY_INTERFACE_NOT_EXPOSED,
	AMBIGUOUS_REPOSITORY_METADATA,
	DUPLICATE_BEAN_ENCOUNTER,
	EXISTING_STP_ADVISOR,
	STP_INFRASTRUCTURE_BEAN,
	CONTEXT_MISMATCH,
	REPOSITORY_CREATED_AFTER_INSERTION_PHASE,
	UNSUPPORTED_PROXY_TYPE
}
