services:
  jenkins-controller:
    ports:
      - "18082:8080"
  jenkins-agent:
    environment:
      JAVA_HOME: /usr/lib/jvm/temurin-26-jdk
      JAVA_TOOL_OPTIONS: -Xmx1024m
      PATH: /opt/apache-maven/bin:/usr/lib/jvm/temurin-26-jdk/bin:/usr/local/bin:/usr/bin:/bin
    volumes:
      - /Users/d061177/work/sonar-java-stp:/opt/ei11/sonar-java:ro
      - /Users/d061177/Programs/apache-maven-3.9.16:/opt/apache-maven:ro
      - /Users/d061177/.m2/repository:/opt/host-m2:ro
      - /Users/d061177/work/asm-poc/codex-worktree/build/functional-test-maven-repository:/opt/stp-m2:ro
      - ei11_map_storage:/opt/ei11/map-storage
  jenkins-agent-1:
    environment:
      JAVA_HOME: /usr/lib/jvm/temurin-26-jdk
      JAVA_TOOL_OPTIONS: -Xmx1024m
      PATH: /opt/apache-maven/bin:/usr/lib/jvm/temurin-26-jdk/bin:/usr/local/bin:/usr/bin:/bin
    volumes:
      - /Users/d061177/work/sonar-java-stp:/opt/ei11/sonar-java:ro
      - /Users/d061177/Programs/apache-maven-3.9.16:/opt/apache-maven:ro
      - /Users/d061177/.m2/repository:/opt/host-m2:ro
      - /Users/d061177/work/asm-poc/codex-worktree/build/functional-test-maven-repository:/opt/stp-m2:ro
      - ei11_map_storage:/opt/ei11/map-storage
  jenkins-agent-2:
    environment:
      JAVA_HOME: /usr/lib/jvm/temurin-26-jdk
      JAVA_TOOL_OPTIONS: -Xmx1024m
      PATH: /opt/apache-maven/bin:/usr/lib/jvm/temurin-26-jdk/bin:/usr/local/bin:/usr/bin:/bin
    volumes:
      - /Users/d061177/work/sonar-java-stp:/opt/ei11/sonar-java:ro
      - /Users/d061177/Programs/apache-maven-3.9.16:/opt/apache-maven:ro
      - /Users/d061177/.m2/repository:/opt/host-m2:ro
      - /Users/d061177/work/asm-poc/codex-worktree/build/functional-test-maven-repository:/opt/stp-m2:ro
      - ei11_map_storage:/opt/ei11/map-storage
  jenkins-agent-3:
    environment:
      JAVA_HOME: /usr/lib/jvm/temurin-26-jdk
      JAVA_TOOL_OPTIONS: -Xmx1024m
      PATH: /opt/apache-maven/bin:/usr/lib/jvm/temurin-26-jdk/bin:/usr/local/bin:/usr/bin:/bin
    volumes:
      - /Users/d061177/work/sonar-java-stp:/opt/ei11/sonar-java:ro
      - /Users/d061177/Programs/apache-maven-3.9.16:/opt/apache-maven:ro
      - /Users/d061177/.m2/repository:/opt/host-m2:ro
      - /Users/d061177/work/asm-poc/codex-worktree/build/functional-test-maven-repository:/opt/stp-m2:ro
      - ei11_map_storage:/opt/ei11/map-storage

volumes:
  ei11_map_storage:
    name: ei11_map_storage
