services:
  jenkins-controller:
    ports:
      - "18082:8080"
  jenkins-agent:
    environment:
      JAVA_HOME: /usr/lib/jvm/temurin-26-jdk
      JAVA_TOOL_OPTIONS: -Xmx1024m
      PATH: /opt/apache-maven/bin:/usr/lib/jvm/temurin-26-jdk/bin:/usr/local/bin:/usr/bin:/bin
    volumes:
      - ${EI11_SONAR_JAVA_DIR:?Set EI11_SONAR_JAVA_DIR}:/opt/ei11/sonar-java:ro
      - ${MAVEN_HOME_DIR:?Set MAVEN_HOME_DIR}:/opt/apache-maven:ro
      - ${HOST_M2_REPOSITORY_DIR:?Set HOST_M2_REPOSITORY_DIR}:/opt/host-m2:ro
      - ${STP_M2_REPOSITORY_DIR:?Set STP_M2_REPOSITORY_DIR}:/opt/stp-m2:ro
      - ei11_map_storage:/opt/ei11/map-storage
  jenkins-agent-1:
    environment:
      JAVA_HOME: /usr/lib/jvm/temurin-26-jdk
      JAVA_TOOL_OPTIONS: -Xmx1024m
      PATH: /opt/apache-maven/bin:/usr/lib/jvm/temurin-26-jdk/bin:/usr/local/bin:/usr/bin:/bin
    volumes:
      - ${EI11_SONAR_JAVA_DIR:?Set EI11_SONAR_JAVA_DIR}:/opt/ei11/sonar-java:ro
      - ${MAVEN_HOME_DIR:?Set MAVEN_HOME_DIR}:/opt/apache-maven:ro
      - ${HOST_M2_REPOSITORY_DIR:?Set HOST_M2_REPOSITORY_DIR}:/opt/host-m2:ro
      - ${STP_M2_REPOSITORY_DIR:?Set STP_M2_REPOSITORY_DIR}:/opt/stp-m2:ro
      - ei11_map_storage:/opt/ei11/map-storage
  jenkins-agent-2:
    environment:
      JAVA_HOME: /usr/lib/jvm/temurin-26-jdk
      JAVA_TOOL_OPTIONS: -Xmx1024m
      PATH: /opt/apache-maven/bin:/usr/lib/jvm/temurin-26-jdk/bin:/usr/local/bin:/usr/bin:/bin
    volumes:
      - ${EI11_SONAR_JAVA_DIR:?Set EI11_SONAR_JAVA_DIR}:/opt/ei11/sonar-java:ro
      - ${MAVEN_HOME_DIR:?Set MAVEN_HOME_DIR}:/opt/apache-maven:ro
      - ${HOST_M2_REPOSITORY_DIR:?Set HOST_M2_REPOSITORY_DIR}:/opt/host-m2:ro
      - ${STP_M2_REPOSITORY_DIR:?Set STP_M2_REPOSITORY_DIR}:/opt/stp-m2:ro
      - ei11_map_storage:/opt/ei11/map-storage
  jenkins-agent-3:
    environment:
      JAVA_HOME: /usr/lib/jvm/temurin-26-jdk
      JAVA_TOOL_OPTIONS: -Xmx1024m
      PATH: /opt/apache-maven/bin:/usr/lib/jvm/temurin-26-jdk/bin:/usr/local/bin:/usr/bin:/bin
    volumes:
      - ${EI11_SONAR_JAVA_DIR:?Set EI11_SONAR_JAVA_DIR}:/opt/ei11/sonar-java:ro
      - ${MAVEN_HOME_DIR:?Set MAVEN_HOME_DIR}:/opt/apache-maven:ro
      - ${HOST_M2_REPOSITORY_DIR:?Set HOST_M2_REPOSITORY_DIR}:/opt/host-m2:ro
      - ${STP_M2_REPOSITORY_DIR:?Set STP_M2_REPOSITORY_DIR}:/opt/stp-m2:ro
      - ei11_map_storage:/opt/ei11/map-storage

volumes:
  ei11_map_storage:
    name: ei11_map_storage
